### PR TITLE
Added citation file

### PR DESCRIPTION
**Pull request by SimaoBolota-MetaCell**
## Description

Hello Adam,

This is Simão from MetaCell. We are working with the Chan Zuckerberg Initiative (CZI) to improve the Napari plugins’ documentation and citation.

To help you adopt the recommended citation format for Napari plugins, we developed a tool that automatically generates a .CFF file containing the information about your plug in. This is how it works:

- Our citation tool analyses and extracts information from your README.md file;
- It prepares a draft of the CITATION.CFF and creates a pull request
- All you have to do is to review the draft of the CITATION.CFF and edit it or approve it!
- Accept the PR and merge it, your CITATION.CFF file will now meet the Napari plugin citation standards

The .CFF is a plain text file with human- and machine-readable citation information for software and datasets.

Some additional notes:

- The CITATION.CFF file naming needs to be as it is, otherwise it won’t be recognized.
- For citations to be recognized in the README.md these need to have either the APA or BibTex format
- Some more information regarding .CFF can be found here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files 

**What is this PR**

- [ ] Bug fix
- [x] Addition of a new feature
- [ ] Other

**Why is this PR needed?**
Some of the information displayed in the CITATION.CFF might not be as the user wants it displayed, so the PR is made to ensure this information is verified.

**What does this PR do?**
Creates a CITATION.CFF, which is the recommended citation format adopted by Napari plugins.

## How has this PR been tested?

Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.

## Is this a breaking change?

No

## Does this PR require an update to the documentation?
No

### CODE REVIEW

**Comment by SimaoBolota-MetaCell** [comment]
Hi Adam,
That's a really good point for me to improve the process.
In the meanwhile and to address your question what I can do is manually remove the doi line before the article references.

**Comment by adamltyson** [comment]
Hi @SimaoBolota-MetaCell, I don't think this fixes the issue. The generated citation still references the name of the paper, but links to the software repository. I would have thought it would be either:
* Citing the paper, with DOI etc (preferred, if relevant)
* Citing the software, with link to the repo (and DOI to zenodo etc. if available)

Currently it's a mix of the two:
```
@software{Tyson_Accurate_determination_of,
author = {Tyson, A. and Vélez-Fort, M. and Rousseau, C. and Cossell, L. and Tsitoura,  C. and Lenzi,  S. and Obenhaus, H. and Claudi, F. and Branco, T. and Margrie, T.},
title = {{Accurate determination of marker location within whole-brain microscopy images}},
url = {https://github.com/brainglobe/brainreg-napari}
}
```

**Comment by SimaoBolota-MetaCell** [comment]
Hi Adam @adamltyson ,
You are right, most of the software could have title that does not match with the article name, and I had it for both the software and article citations.
To correct this the main citation is now focused on information retrieved from within the GitHub Repo, such as contributors, repository name and used as the citation software, while the article citation is indexed inside the references section by scraping the README.md.

Something of this sorts:

image

For your plugin in particular, the main citation would have as:
-  title: brain-reg napari
- authors: contributors of the github repo
- url: url of the github repo

and the references subsection would have all the remaining data with all authors names, article title, DOI, article url, etc.

Let me know what you think of this approach so I can create another Pull request

**Comment by adamltyson** [comment]
Hey @SimaoBolota-MetaCell. Is it possible to make the paper the default citation? At least for those working in academia, where there is a relevant article, it would be preferable.

**Comment by SimaoBolota-MetaCell** [comment]
Hi @adamltyson as suggested we improved the process to consider the article or book citations as the preferred citation. If there is no article/book citation information, no preferred-citation group is created and therefore the main citation will be for the software. 

Made a Pull Request with the according changes.

Please let me know what you think
and again thank you for the great suggestions

**Review by adamltyson — APPROVED** [review]

**Comment by SimaoBolota-MetaCell** [comment]
Great, thanks for all the valuable input! @adamltyson

**Pull request merged**
